markdown: kramdown
theme: jekyll-theme-hacker
title: Вадим Ушаков — персональный сайт
permalink: /:categories/:year/:title/
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-theme-hacker
exclude:
  - Gemfile
  - Gemfile.lock

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
