markdown: kramdown
theme: jekyll-theme-hacker
title: wandien's personal home page
permalink: /:categories/:year/:title/
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

tag_dir: tag
